### ISSUE TITLE
Would you be willing to share the demo project?

### ISSUE THREAD

**Issue by redthing1** [nekotogd/Godot_BoTW_Toon_Shader#1]
Would you be willing to share the demo project/scene that is featured in your videos?

**Comment by nekotogd** [comment]
Sorry for the late reply.

I haven't actually made it a separate demo scene, it was coupled together with a project I was working on.

I'll decouple the files and commit them to the repo so you can clone it.

**Comment by redthing1** [comment]
Thank you!!

**Comment by nekotogd** [comment]
Done!

Here: [demo_scene branch](https://github.com/nekotogd/Godot_BoTW_Toon_Shader/tree/demo_scene)

**Comment by redthing1** [comment]
Awesome!
